version: "3"
services:
    web:
       image: "feltonvillain/headhuntapi:latest"
       ports:
          - "5000:80"
       depends_on:
          - db
    site:
       image: "feltonvillain/headhuntreview:latest"
       ports:
          - "4200:80"
       depends_on:
          - db
    db:
        image: "feltonvillain/headhuntdb"
        environment:
            SA_PASSWORD: "L@rc0mb3"
            ACCEPT_EULA: "Y"
