version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install dependencies
        command: |
          apk update
          apk add --no-cache \
            curl curl-dev bash
          apk add --no-cache \
            py-pip=9.0.0-r1
          pip install \
            docker-compose==1.12.0 \
            awscli==1.11.76
    - restore_cache:
        keys:
          - v1-{{ .Branch }}
        paths:
          - /caches/headhuntreview_v2.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/headhuntreview_v2.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=headhuntreview_v2 -t headhuntreview_v2 .
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/headhuntreview_v2.tar headhuntreview_v2
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/headhuntreview_v2.tar
deploy_to_staging:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "feltonvillain/headhuntreview"
      - GOOGLE_PROJECT_ID: "headhunterreviews-ffb31"
      - GOOGLE_COMPUTE_ZONE: "us-central1-a"
      - GOOGLE_CLUSTER_NAME: "headhuntreviews-cluster"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker build and push
          command: |
            docker build -t ${PROJECT_NAME} .
            docker tag ${PROJECT_NAME}:${CIRCLE_SHA1}
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PW
            docker push ${PROJECT_NAME}:${CIRCLE_SHA1}
